### PR TITLE
Adding Azure help

### PR DESCRIPTION
**Pull request by shinji62**
Adding Azure in the help
Plus others fixing some static check issues.
To be merge once Azure is GA

### CODE REVIEW

**Review by posriniv — APPROVED** [review]
Looks good to me!

**Review by cdavid — APPROVED** [review]

**Review by kc-yb — COMMENTED** [review]
Had a high level question - since we won't we ready for Azure prod in some time how will these changes be staged since CLI has a different release cycle. 

@cdavid Appreciate suggestions/way-forward on how we can handle these changes which are not ready in prod?

**Comment by kc-yb** [comment]
I understand that https://yugabyte.atlassian.net/browse/CLOUDGA-12220 is in progress - but CLI could be released soon. Perhaps we need to defer this change for now?

**Comment by shinji62** [comment]
@kc-yb I just pinged @cdavid those change are ok for now, Azure is around the corner, plus this is just help changed. 

I don t think that gonna make a huge impact.

To respond to your question, I think we can put some of them behind a flag.

**Pull request merged**
