### PR TITLE
[CLOUDGA-23248] : CLI Get Cluster - Add CP Status

### PR DESCRIPTION
**Pull request by adityakaushik99-yb**
Tested with cluster on devcloud

### CODE REVIEW

**Review by posriniv — APPROVED** [review]
Looks good to me!

**Comment by harshitha-yb** [comment]
> Looks good to me!

Should/can this be hidden if the FF is not on?

**Comment by posriniv** [comment]
> > Looks good to me!
> 
> Should/can this be hidden if the FF is not on?

Yeah, if it is not public yet and behind a feature flag, it has to be hidden. Please use the following PRs for reference:

https://github.com/yugabyte/ybm-cli/commit/400b247fb52b790758a8df910224ef8a05e57021#diff-bcf06a220f40318c8aa7a4383cf9255bc9f7691d036b41bea3b3ac1dae41c529R243

https://github.com/yugabyte/ybm-cli/commit/90c548af08d8630e6c6c3ca05a591804bf9782b8#diff-bcf06a220f40318c8aa7a4383cf9255bc9f7691d036b41bea3b3ac1dae41c529R278

Any new ideas are welcome too.

**Comment by harshitha-yb** [comment]
Yes the connection pooling enable/disable commands are under the FFs but this is a column in the list/get cluster commands. Can we not print this if the FF isn't enabled? cc: @adityakaushik99-yb

**Comment by adityakaushik99-yb** [comment]
> Yes the connection pooling enable/disable commands are under the FFs but this is a column in the list/get cluster commands. Can we not print this if the FF isn't enabled? cc: @adityakaushik99-yb

Not sure if that's possible, but FWIW having discussed this with Ranga and Krishnan, they were okay with this being visible if there isn't a way to hide it.

**Comment by posriniv** [comment]
@adityakaushik99-yb 
I think we can hide the column. If you see the references I have given carefully, there are two formatters [https://github.com/yugabyte/ybm-cli/commit/400b247fb52b790758a8df910224ef8a05e57021#diff-ec0e1226ad0a30e67f3817df0[…]338ec042816cc25d5ee1c1fd3ac6a90](https://github.com/yugabyte/ybm-cli/commit/400b247fb52b790758a8df910224ef8a05e57021#diff-ec0e1226ad0a30e67f3817df0a04c3223338ec042816cc25d5ee1c1fd3ac6a90) and [https://github.com/yugabyte/ybm-cli/commit/400b247fb52b790758a8df910224ef8a05e57021#diff-34a06783171303786c49a8bba[…]05745fb75f48a13b4eed2fbddae1b75](https://github.com/yugabyte/ybm-cli/commit/400b247fb52b790758a8df910224ef8a05e57021#diff-34a06783171303786c49a8bbaa6818dfb05745fb75f48a13b4eed2fbddae1b75)
The v2 command invokes a different formatter thereby showing a different set of columns in the output.

**Comment by posriniv** [comment]
@adityakaushik99-yb Looks good, please check the build once.

**Pull request merged**
