### PR TITLE
[CLOUDGA-14373]: Add support for adding EAR to existing cluster 

### PR DESCRIPTION
**Pull request by arishta-yb**
Modified the updateCmk api to allow adding CMK to non EAR enabled clusters.

### CODE REVIEW

**Comment by shinji62** [comment]
Even if the PR seems ok, I think it's time to add some test around this command.

**Review by kc-yb — APPROVED** [review]
Please get additional review

**Comment by posriniv** [comment]
Looks okay to me. 

> Even if the PR seems ok, I think it's time to add some test around this command.

Agree with @shinji62 here.

**Comment by arishta-yb** [comment]
Here is the ticket link for adding UTs for CMK: 
https://yugabyte.atlassian.net/browse/CLOUDGA-14392

**Pull request merged**
